// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: pkg/tenant/pb/tenant.proto

package tenantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PlanCode            string                 `protobuf:"bytes,5,opt,name=plan_code,json=planCode,proto3" json:"plan_code,omitempty"`
	MaxTokensMonth      int64                  `protobuf:"varint,6,opt,name=max_tokens_month,json=maxTokensMonth,proto3" json:"max_tokens_month,omitempty"`
	MaxRequestsMinute   int64                  `protobuf:"varint,7,opt,name=max_requests_minute,json=maxRequestsMinute,proto3" json:"max_requests_minute,omitempty"`
	DefaultModel        string                 `protobuf:"bytes,8,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	EnableSemanticCache bool                   `protobuf:"varint,9,opt,name=enable_semantic_cache,json=enableSemanticCache,proto3" json:"enable_semantic_cache,omitempty"`
	CacheTtlSecs        int32                  `protobuf:"varint,10,opt,name=cache_ttl_secs,json=cacheTtlSecs,proto3" json:"cache_ttl_secs,omitempty"`
	MaxPromptTokens     int32                  `protobuf:"varint,11,opt,name=max_prompt_tokens,json=maxPromptTokens,proto3" json:"max_prompt_tokens,omitempty"`
	MaxCompletionTokens int32                  `protobuf:"varint,12,opt,name=max_completion_tokens,json=maxCompletionTokens,proto3" json:"max_completion_tokens,omitempty"`
	PolicyConfig        []byte                 `protobuf:"bytes,13,opt,name=policy_config,json=policyConfig,proto3" json:"policy_config,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_pkg_tenant_pb_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tenant) GetPlanCode() string {
	if x != nil {
		return x.PlanCode
	}
	return ""
}

func (x *Tenant) GetMaxTokensMonth() int64 {
	if x != nil {
		return x.MaxTokensMonth
	}
	return 0
}

func (x *Tenant) GetMaxRequestsMinute() int64 {
	if x != nil {
		return x.MaxRequestsMinute
	}
	return 0
}

func (x *Tenant) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *Tenant) GetEnableSemanticCache() bool {
	if x != nil {
		return x.EnableSemanticCache
	}
	return false
}

func (x *Tenant) GetCacheTtlSecs() int32 {
	if x != nil {
		return x.CacheTtlSecs
	}
	return 0
}

func (x *Tenant) GetMaxPromptTokens() int32 {
	if x != nil {
		return x.MaxPromptTokens
	}
	return 0
}

func (x *Tenant) GetMaxCompletionTokens() int32 {
	if x != nil {
		return x.MaxCompletionTokens
	}
	return 0
}

func (x *Tenant) GetPolicyConfig() []byte {
	if x != nil {
		return x.PolicyConfig
	}
	return nil
}

type GetTenantByAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByAPIKeyRequest) Reset() {
	*x = GetTenantByAPIKeyRequest{}
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByAPIKeyRequest) ProtoMessage() {}

func (x *GetTenantByAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*GetTenantByAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tenant_pb_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantByAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type GetTenantByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByIDRequest) Reset() {
	*x = GetTenantByIDRequest{}
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByIDRequest) ProtoMessage() {}

func (x *GetTenantByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTenantByIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tenant_pb_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantByIDRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tenant_pb_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tenant_pb_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

var File_pkg_tenant_pb_tenant_proto protoreflect.FileDescriptor

const file_pkg_tenant_pb_tenant_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/tenant/pb/tenant.proto\x12\ttenant.v1\"\xd3\x03\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tplan_code\x18\x05 \x01(\tR\bplanCode\x12(\n" +
	"\x10max_tokens_month\x18\x06 \x01(\x03R\x0emaxTokensMonth\x12.\n" +
	"\x13max_requests_minute\x18\a \x01(\x03R\x11maxRequestsMinute\x12#\n" +
	"\rdefault_model\x18\b \x01(\tR\fdefaultModel\x122\n" +
	"\x15enable_semantic_cache\x18\t \x01(\bR\x13enableSemanticCache\x12$\n" +
	"\x0ecache_ttl_secs\x18\n" +
	" \x01(\x05R\fcacheTtlSecs\x12*\n" +
	"\x11max_prompt_tokens\x18\v \x01(\x05R\x0fmaxPromptTokens\x122\n" +
	"\x15max_completion_tokens\x18\f \x01(\x05R\x13maxCompletionTokens\x12#\n" +
	"\rpolicy_config\x18\r \x01(\fR\fpolicyConfig\"3\n" +
	"\x18GetTenantByAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"3\n" +
	"\x14GetTenantByIDRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\">\n" +
	"\x11GetTenantResponse\x12)\n" +
	"\x06tenant\x18\x01 \x01(\v2\x11.tenant.v1.TenantR\x06tenant2\xab\x01\n" +
	"\rTenantService\x12P\n" +
	"\vGetByAPIKey\x12#.tenant.v1.GetTenantByAPIKeyRequest\x1a\x1c.tenant.v1.GetTenantResponse\x12H\n" +
	"\aGetByID\x12\x1f.tenant.v1.GetTenantByIDRequest\x1a\x1c.tenant.v1.GetTenantResponseBCZAgithub.com/jeanmolossi/kalika-eco-ai-proxy/pkg/tenant/pb;tenantpbb\x06proto3"

var (
	file_pkg_tenant_pb_tenant_proto_rawDescOnce sync.Once
	file_pkg_tenant_pb_tenant_proto_rawDescData []byte
)

func file_pkg_tenant_pb_tenant_proto_rawDescGZIP() []byte {
	file_pkg_tenant_pb_tenant_proto_rawDescOnce.Do(func() {
		file_pkg_tenant_pb_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tenant_pb_tenant_proto_rawDesc), len(file_pkg_tenant_pb_tenant_proto_rawDesc)))
	})
	return file_pkg_tenant_pb_tenant_proto_rawDescData
}

var file_pkg_tenant_pb_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_tenant_pb_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                   // 0: tenant.v1.Tenant
	(*GetTenantByAPIKeyRequest)(nil), // 1: tenant.v1.GetTenantByAPIKeyRequest
	(*GetTenantByIDRequest)(nil),     // 2: tenant.v1.GetTenantByIDRequest
	(*GetTenantResponse)(nil),        // 3: tenant.v1.GetTenantResponse
}
var file_pkg_tenant_pb_tenant_proto_depIdxs = []int32{
	0, // 0: tenant.v1.GetTenantResponse.tenant:type_name -> tenant.v1.Tenant
	1, // 1: tenant.v1.TenantService.GetByAPIKey:input_type -> tenant.v1.GetTenantByAPIKeyRequest
	2, // 2: tenant.v1.TenantService.GetByID:input_type -> tenant.v1.GetTenantByIDRequest
	3, // 3: tenant.v1.TenantService.GetByAPIKey:output_type -> tenant.v1.GetTenantResponse
	3, // 4: tenant.v1.TenantService.GetByID:output_type -> tenant.v1.GetTenantResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_tenant_pb_tenant_proto_init() }
func file_pkg_tenant_pb_tenant_proto_init() {
	if File_pkg_tenant_pb_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tenant_pb_tenant_proto_rawDesc), len(file_pkg_tenant_pb_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_tenant_pb_tenant_proto_goTypes,
		DependencyIndexes: file_pkg_tenant_pb_tenant_proto_depIdxs,
		MessageInfos:      file_pkg_tenant_pb_tenant_proto_msgTypes,
	}.Build()
	File_pkg_tenant_pb_tenant_proto = out.File
	file_pkg_tenant_pb_tenant_proto_goTypes = nil
	file_pkg_tenant_pb_tenant_proto_depIdxs = nil
}
