name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ubuntu:
    strategy:
      matrix:
        go: [stable, "1.25"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -race -timeout 10m ./...
